export const SITE = {
  title: "sungjunyoung",
  description: "❤️ cloud native, sungjunyoung's blog",
  author: "Junyoung, Sung",
  url: "https://blog.sungjunyoung.dev",
  /** The posts are written in Korean; search engines target on this. */
  lang: "ko",
  locale: "ko_KR",
  postsPerPage: 5,
  googleAnalyticsId: "G-CMFR9WZ898",
  adsenseClient: "ca-pub-6425995549268997",
  /** 1200x630 social cards, regenerated by scripts/make-og-card.py. */
  ogImage: "/assets/og/card.gif",
  /** Static twin of the card, for scrapers that skip GIF. PNG rather than
      WebP: several major scrapers still reject WebP for og:image. */
  ogImageFallback: "/assets/og/card.png",
  ogImageWidth: 1200,
  ogImageHeight: 630,
  github: "https://github.com/sungjunyoung",
  linkedin: "https://www.linkedin.com/in/junyoung-sung-986412121/",
} as const;

export const MENU = [{ name: "About", url: "/about/" }] as const;

export const LABELS = {
  readMore: "Read More",
  readOtherPosts: "Read other posts",
  newerPosts: "Newer posts",
  olderPosts: "Older posts",
  menuMore: "Show more",
} as const;

/**
 * Hugo rendered `.Date.Format "2006-01-02"` in the date's own offset, and every
 * post is authored with +09:00. Formatting in Asia/Seoul reproduces the exact
 * strings the old site served, so permalinks and dates stay stable.
 */
const DATE_FORMATTER = new Intl.DateTimeFormat("en-CA", {
  timeZone: "Asia/Seoul",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
});

export function formatDate(date: Date): string {
  return DATE_FORMATTER.format(date);
}
